#!/bin/bash

#PBS -A mfb9_a_g_sc_default
#PBS -l nodes=1:ppn=1
#PBS -l pmem=32gb
#PBS -l walltime=24:00:00

#PBS -m ea
#PBS -M rbz5100@psu.edu

# Note the start time and location in case an error occurs
echo "Job started on `hostname` at `date`"

# Change to the directory we launched the script from and launch the simulation
cd $PBS_O_WORKDIR
./MaSim -i scaling-#SCALING#.yml --mc

# Note the end time
echo "Job ended at `date`"
